# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/155lerUTc7UtQEvPCcs1BsSGGtFahzPOo
"""

import streamlit as st
import numpy as np
import pickle
import re
import os
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Konfigurasi Halaman Dasar
st.set_page_config(page_title="Versi 1 - IMDB Sentiment", page_icon="🎬")

st.title("🎬 IMDB Movie Review Sentiment Analysis")
st.write("**Versi 1:** Pengujian Fitur Inti Klasifikasi Sentimen Teks")
st.markdown("---")

@st.cache_resource
def load_sentiment_model():
    model_path = 'sentiment_GRU_cfg1_seq100.h5'
    if os.path.exists(model_path):
        return load_model(model_path)
    return None

@st.cache_resource
def get_tokenizer():
    if os.path.exists('tokenizer.pkl'):
        with open('tokenizer.pkl', 'rb') as handle:
            return pickle.load(handle)
    return None

def preprocess_text(text, tokenizer, max_len=100):
    text = text.lower()
    text = re.sub(r'<[^>]*>', '', text)
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    sequences = tokenizer.texts_to_sequences([text])
    padded = pad_sequences(sequences, maxlen=max_len, padding='post', truncating='post')
    return padded

# Load model & tokenizer
model = load_sentiment_model()
tokenizer = get_tokenizer()

if model is None or tokenizer is None:
    st.error("Model atau Tokenizer tidak ditemukan! Pastikan file .h5 dan .pkl sudah di-upload ke repository.")
else:
    user_input = st.text_area("Masukkan review film (Bahasa Inggris):", "This movie was absolutely amazing! I loved every second of it.")

    if st.button("Analisis Sentimen"):
        if user_input.strip() == "":
            st.warning("Teks tidak boleh kosong.")
        else:
            with st.spinner("Menganalisis..."):
                processed_text = preprocess_text(user_input, tokenizer)
                prediction = model.predict(processed_text)[0][0]

                st.subheader("Hasil Prediksi:")
                if prediction > 0.5:
                    st.success(f"🌟 POSITIF (Kepercayaan: {prediction:.2%})")
                else:
                    st.error(f"💔 NEGATIF (Kepercayaan: {(1-prediction):.2%})")
